export const projects = [
  {
    img: "https://iili.io/WjTTaj.png",
    title: "Onn_Bikes clone",
    des: "Today in this world, A website is a part of initial building block of every business. not having a website for your business is not recommended at all Whenever I go to a new city where I don’t know anyone or never been before it gets me little scared than, I really felt like I need my own bike to explore the city and go wherever I need, that’s exactly where our website will help you. it provides you every kind of bike whatever you’re looking for.",
    demo: "",
    live: "https://onnbikes.netlify.app/",
    gitHub: "https://github.com/Arora-Shivam/ONN-BIKES-CW",
    technologies: ["HTML", "CSS", "javaScript"],
  },
  {
    img: "https://iili.io/VQV6Na.png",
    title: "BobbiBrown Clone",
    des: "It is an online e-commerce beauty cosmetic website which particularly cater the needs to women. .",
    live: "https://grand-sunflower-c54efa.netlify.app/",
    gitHub: "https://github.com/Tushar504/Fw15-Bobbi-Brown--Project",
    technologies: ["HTML", "CSS", "javaScript"],
  },
  {
    img: "https://iili.io/WjTg94.png",
    title: "Onn_Bikes clone",
    des: "Today in this world, A website is a part of initial building block of every business. not having a website for your business is not recommended at all.",
    demo: "",
    live: "https://sharp-brahmagupta-a8b2e3.netlify.app/",
    gitHub: "https://github.com/Ritesh6997/ONN-BIke-Complete-Project",
    technologies: ["Mongodb", "Node.js", "HTML", "CSS", "javaScript"],
  },
  {
    img: "https://iili.io/WjuRls.jpg",
    title: "Mama_Earth_Clone",
    des: "In this project we have tried to make a clone of MamaEarth website. With our efforts and the technology stack,we were able to clone the front end, integrated it with backend and added similar looks and features.The Mamaearth company is an Indian brand and is based out of Gurugram, Haryana.",
    demo: "",
    live: "https://mama-earth.netlify.app/",
    gitHub: "https://github.com/bharathk07/mamaearth-clone",
    technologies: ["Mongodb", "Node.js", "HTML", "CSS", "javaScript"],
  },

  // {
  // 	img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
  // 	title: 'Clone of Fitness Blender',
  // 	des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
  // 	demo: '',
  // 	live: 'https://anshusagar.github.io/FitnessBlender/',
  // 	gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
  // 	technologies: ['HTML', 'CSS', 'javaScript'],
  // },
  // {
  // 	img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
  // 	title: 'Mailchimp Clone',
  // 	des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
  // 	demo: '',
  // 	live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
  // 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
  // 	technologies: ['HTML', 'CSS', 'javaScript'],
  // },
];
